# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-08-26 05:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msg', models.CharField(default='', max_length=70)),
                ('sender_profile_id', models.IntegerField(null=True)),
                ('sender_name', models.CharField(max_length=60)),
                ('reciever_profile_id', models.IntegerField(null=True)),
                ('seen_status', models.BooleanField(default=False)),
                ('send_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-send_time'],
            },
        ),
    ]
